name: Generate ARM templates docs
on:
  push:
    branches: [ main ]
jobs:
  arm_docs:
    name: Generate ARM template docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate ARM markdowns
      run: |
        Install-Module -Name 'PSDocs.Azure' -Repository PSGallery -force;
        #$VerbosePreference = 'Continue';
        Get-AzDocTemplateFile | ForEach-Object {
          $TemplateFile = Get-Item -Path $_.TemplateFile;
          $RepoName = $TemplateFile.Directory.Parent.Name;
          $Template = Get-Content $TemplateFile |ConvertFrom-Json;
          $Version = $Template.ContentVersion;
          $docName = "README";
          $ReadmeHeader = "[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMultiCloudDeployment%2F$($RepoName)%2F$($Version)%2Fazuredeploy.json)"
          # Generate markdown
          Invoke-PSDocument -Module PSDocs.Azure -OutputPath "out/docs" -InputObject $TemplateFile.FullName -InstanceName $docName;
        };
        $Readme = Get-Content "out/docs/$($docName).md";
        Write-Output $ReadmeHeader |Out-File "out/docs/$($docName).md" -Force;
        Write-Output $Readme |Out-File "out/docs/$($docName).md" -Append;
        #Get-Content "out/docs/$($docName).md";
        Move-Item "out/docs/$($docName).md" . -Force
      shell: pwsh
    - name: Setup Git Config
      run:
        git config user.name "GitHub Action";
        git config user.email "<>";
    - name: Update ReadME
      run:
        git add *;
        git commit -m "Updating README with latest documentation";
        git push origin main
